### PR TITLE
un register event when componet unmount

### PR DESCRIPTION
**Pull request by hamza4600**
I apologize for any confusion I close the previous branch so I made changes in this branch 
hope will be soon merge 
 cc : @Zwyx  @tomokendo  @mattgarven

### CODE REVIEW

**Review by Zwyx — APPROVED** [review]
Excellent, thanks for that!

**Review by RJP45 — APPROVED** [review]

**Review by RJP45 — APPROVED** [review]

**Review by owlyowl — APPROVED** [review]

**Comment by hamzabnb** [comment]
Hello can you guys create a repo for next js also I have done alot for work and i can push my code to that also those are Serve componenets .
cc : @owlyowl  @RJP45  @Zwyx

**Comment by Zwyx** [comment]
Great idea, thanks Hamza. I'll chat with my team and let you know. Please note that we are a bit busy these days, so it might take a little while.

**Comment by Zwyx** [comment]
Hey Hamza, would you be keen to make this in your own account? Then we could fork it or provide it as an Okendo community solution (with credit).

**Comment by hamza4600** [comment]
okay i will make it and tell you about this  hope it will be done by Sunday

**Comment by hamza4600** [comment]
Kindly check out this code any suggestion tell me 
https://github.com/hamza4600/okendo-next
@Zwyx

**Comment by Zwyx** [comment]
Hey Hamza, thanks again for your work and your interest in Okendo! This Next.js demo appears to be very similar to the existing `okendo-reactjs-example`. I'm not sure having and maintaining both is necessary. I'll check with my team. Also, it appears to not make use of React server components (maybe you meant that it takes advantages of Next's SSR?).

**Comment by hamza4600** [comment]
It does not behave properly when use Server Component .
I was also think to create a new Page where you can test your app you will enter `App Id and Product Id `is will show the okendo reviews on the page

**Pull request merged**
